name             'julius'
maintainer       'Yosuke Matsusaka'
maintainer_email 'yosuke.matsusaka@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures Julius'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'build-essential'
depends          'apt'
depends          'cvs'
